AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false